# youtube_uploader.py
import os
import pickle
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.http import MediaFileUpload

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def upload_to_youtube(file_path, title):
    creds = None

    # Load token from previous login
    if os.path.exists("token.pickle"):
        with open("token.pickle", "rb") as token:
            creds = pickle.load(token)

    # If no valid credentials available, log in
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("client_secrets.json", SCOPES)
            creds = flow.run_local_server(
    port=8091,
    host='0.0.0.0',  # Gitpod binds this to a public URL
    redirect_uri_trailing_slash=False
)


        with open("token.pickle", "wb") as token:
            pickle.dump(creds, token)

    youtube = build("youtube", "v3", credentials=creds)

    request_body = {
        "snippet": {
            "title": title,
            "description": "Generated by AlannahAI",
            "tags": ["AlannahAI", "Auto AI Video", "Python YouTube Bot"],
            "categoryId": "27"  # Education
        },
        "status": {
            "privacyStatus": "unlisted"
        }
    }

    media = MediaFileUpload(file_path, resumable=True)

    request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media
    )

    response = request.execute()
    print("📺 Uploaded! View at:")
    print(f"🔗 https://youtube.com/watch?v={response['id']}")
